#!/usr/bin/env node

var common = require('./common'),
    nodeStatic = require('node-static'),
    watch = require('glob-watcher');

function build(done) {
  console.log("Rebuilding...")
  common
    .build(function(err) {
      if (err) { throw err; }
      console.log("Rebuilt.");
    });
  done();
}

var serve = new nodeStatic.Server('build');
require('http').createServer((req, res) => {
  req.addListener('end', () => serve.serve(req, res));
  req.resume();
}).listen(1313);

watch([
  "src/**/*",
  "assets/**/*",
  "layouts/**/*"
], { ignoreInitial: false }, build);
