#!/usr/bin/env node

var common = require('./common'),
    serve = require('metalsmith-serve'),
    watch = require('metalsmith-watch');

// Fix build function so it runs without parameters
common
  .use(serve({
    port: 1313,
    verbose: true
  }))
  .use(watch({
    paths: {
      "${source}/**/*": true,
      "assets/**/*": true,
      "layouts/**/*": true,
    }
  }))
  .build(function(err) {
    if (err) { throw err; }
  });
